---
- name: "PLAY 1: Collect information from all routers"
  hosts: "all"
  tasks:
    - name: "TASK 1: Collect system facts"
      ios_facts:
        gather_subset:
          - "interfaces"
      register: "facts"

    - name: "TASK 2: Run verification commands"
      ios_command:
        commands: "{{ commands }}"
      register: "cli_output"

    - name: "TASK 3: Ensure outputs/ directory exists"
      file:
        path: "outputs"
        state: "directory"
      run_once: true
      delegate_to: "localhost"

    - name: "TASK 4: Save data to host-specific file"
      template:
        src: "templates/ios_data.j2"
        dest: "{{ playbook_dir }}/outputs/{{ inventory_hostname }}_facts.txt"
      delegate_to: "localhost"
...
